[[main]]
  name = "portfolio"
  pageRef = "about/portfolio"
  weight = 10

[[main]]
  name = "projects"
  pageRef = "about/projects"
  weight = 20

[[main]]
  name = "notes"
  pageRef = "about/notes"
  weight = 30

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 40

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"
