# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Notes"
  weight = 30

[[main]]
  name = "computer vision"
  parent = "Notes"
  pageRef = "notes/computer_vision"
  weight = 31

[[main]]
  name = "computer graphics"
  parent = "Notes"
  pageRef = "notes/computer_graphics"
  weight = 32

[[main]]
  name = "linguaggi e modelli computazionali"
  parent = "Notes"
  pageRef = "notes/linguaggi_modelli_computazionali"
  weight = 33

[[main]]
  name = "tecnologie basi di dati"
  parent = "Notes"
  pageRef = "notes/tecnologie_basi_dati"
  weight = 34

[[main]]
  name = "datamining"
  parent = "Notes"
  pageRef = "notes/datamining"
  weight = 35

[[main]]
  name = "mobile systems"
  parent = "Notes"
  pageRef = "notes/mobile_systems"
  weight = 36

[[main]]
  name = "technologies"
  parent = "Notes"
  pageRef = "technologies"
  weight = 90

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
