[[main]]
  name = "portfolio"
  pageRef = "about/portfolio"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"
